package maajoukkue.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import maajoukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.10 12:18:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HiihtajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi132 */
  @Test
  public void testRekisteroi132() {    // Hiihtaja: 132
    Hiihtaja klaebo = new Hiihtaja(); 
    assertEquals("From: Hiihtaja line: 134", 0, klaebo.getJid()); 
    klaebo.rekisteroi(); 
    assertEquals("From: Hiihtaja line: 136", 1, klaebo.getJid()); 
    Hiihtaja pellegrino = new Hiihtaja(); 
    pellegrino.rekisteroi(); 
    assertEquals("From: Hiihtaja line: 139", 2, pellegrino.getJid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString171 */
  @Test
  public void testToString171() {    // Hiihtaja: 171
    Hiihtaja iivo = new Hiihtaja(); 
    iivo.parse("0   |   Iivo Niskanen  |31|1   |4|2    |3|8|21  |Perinteisen taitaja, Vieremalta..."); 
    assertEquals("From: Hiihtaja line: 174", "0|Iivo Niskanen|31|1|4|2|3|8|21|Perinteisen taitaja, Vieremalta...", iivo.toString()); 
  } // Generated by ComTest END
}