package maajoukkue.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import maajoukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.10 12:18:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HiihtajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista50 
   * @throws SailoException when error
   */
  @Test
  public void testPoista50() throws SailoException {    // Hiihtajat: 50
    Hiihtajat hiihtajat = new Hiihtajat(); 
    Hiihtaja iivo = new Hiihtaja(), pera = new Hiihtaja(); 
    assertEquals("From: Hiihtajat line: 54", 0, hiihtajat.getLkm()); 
    iivo.rekisteroi(); pera.rekisteroi(); 
    hiihtajat.lisaa(iivo); assertEquals("From: Hiihtajat line: 56", 1, hiihtajat.getLkm()); 
    hiihtajat.lisaa(pera); assertEquals("From: Hiihtajat line: 57", 2, hiihtajat.getLkm()); 
    hiihtajat.poista(2); assertEquals("From: Hiihtajat line: 58", 1, hiihtajat.getLkm()); 
    hiihtajat.poista(1); assertEquals("From: Hiihtajat line: 59", 0, hiihtajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa128 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa128() throws SailoException {    // Hiihtajat: 128
    Hiihtajat hiihtajat = new Hiihtajat(); 
    Hiihtaja iivo = new Hiihtaja(), pera = new Hiihtaja(); 
    assertEquals("From: Hiihtajat line: 132", 0, hiihtajat.getLkm()); 
    hiihtajat.lisaa(iivo); assertEquals("From: Hiihtajat line: 133", 1, hiihtajat.getLkm()); 
    hiihtajat.lisaa(pera); assertEquals("From: Hiihtajat line: 134", 2, hiihtajat.getLkm()); 
    hiihtajat.lisaa(iivo); assertEquals("From: Hiihtajat line: 135", 3, hiihtajat.getLkm()); 
    assertEquals("From: Hiihtajat line: 136", iivo, hiihtajat.anna(0)); 
    assertEquals("From: Hiihtajat line: 137", pera, hiihtajat.anna(1)); 
    assertEquals("From: Hiihtajat line: 138", iivo, hiihtajat.anna(2)); 
    assertEquals("From: Hiihtajat line: 139", false, hiihtajat.anna(1) == iivo); 
    assertEquals("From: Hiihtajat line: 140", true, hiihtajat.anna(1) == pera); 
    try {
    assertEquals("From: Hiihtajat line: 141", iivo, hiihtajat.anna(3)); 
    fail("Hiihtajat: 141 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    hiihtajat.lisaa(iivo); assertEquals("From: Hiihtajat line: 142", 4, hiihtajat.getLkm()); 
    hiihtajat.lisaa(iivo); assertEquals("From: Hiihtajat line: 143", 5, hiihtajat.getLkm()); 
    hiihtajat.lisaa(iivo); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta198 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta198() throws SailoException {    // Hiihtajat: 198
    Hiihtajat hiihtajat = new Hiihtajat(); 
    Hiihtaja iivo = new Hiihtaja(); 
    Hiihtaja pera = new Hiihtaja(); 
    iivo.tayta(); 
    String hakemisto = "testisuomi"; 
    File dir = new File(hakemisto); 
    File ftied = new File(hakemisto+"/yleistiedot.dat"); 
    dir.mkdir(); 
    try {
    ftied.createNewFile(); 
    assertEquals("From: Hiihtajat line: 215", false, ftied.createNewFile()); 
    } catch (IOException e){
    System.out.println("Ei saa luettua"); 
    }
    try {
    hiihtajat.lueTiedostosta("eioleolemassa"); 
    fail("Hiihtajat: 219 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    hiihtajat.lisaa(iivo); 
    hiihtajat.lisaa(pera); 
    hiihtajat.tallenna(hakemisto); 
    Hiihtajat hiihtajat2 = new Hiihtajat(); 
    hiihtajat2.lisaa(pera); 
    hiihtajat.anna(0).getNimi().equals(iivo.getNimi()); 
    assertEquals("From: Hiihtajat line: 229", true, ftied.delete()); 
    assertEquals("From: Hiihtajat line: 230", true, dir.delete()); 
  } // Generated by ComTest END
}