package maajoukkue.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import maajoukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.10 10:53:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MaajoukkueTest {
    //
}