package maajoukkue.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import maajoukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.10 12:18:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SeuraTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi49 */
  @Test
  public void testRekisteroi49() {    // Seura: 49
    Seura seura1 = new Seura(); 
    assertEquals("From: Seura line: 51", 0, seura1.getTunnusNro()); 
    seura1.rekisteroi(); 
    Seura seura2 = new Seura(); 
    seura2.rekisteroi(); 
    int n1 = seura1.getTunnusNro(); 
    int n2 = seura2.getTunnusNro(); 
    assertEquals("From: Seura line: 57", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString89 */
  @Test
  public void testToString89() {    // Seura: 89
    Seura puijo = new Seura(); 
    puijo.parse("0    |     Puijon hiihtoseura"); 
    assertEquals("From: Seura line: 92", "0|Puijon hiihtoseura", puijo.toString()); 
  } // Generated by ComTest END
}